# Form implementation generated from reading ui file 'c:\Users\maciek\Desktop\Projekty_github\TODO_app\Code\win.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 700)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 430, 150))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.headerLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.headerLayout.setContentsMargins(0, 0, 0, 0)
        self.headerLayout.setObjectName("headerLayout")
        self.labelGreeting = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setWeight(75)
        self.labelGreeting.setFont(font)
        self.labelGreeting.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelGreeting.setObjectName("labelGreeting")
        self.headerLayout.addWidget(self.labelGreeting)
        self.labelProjectsNum = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.labelProjectsNum.setFont(font)
        self.labelProjectsNum.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelProjectsNum.setObjectName("labelProjectsNum")
        self.headerLayout.addWidget(self.labelProjectsNum)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 170, 430, 520))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 410, 500))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(10, 10, 390, 120))
        self.frame.setObjectName("frame")
        self.verticalLayoutFrame = QtWidgets.QVBoxLayout(parent=self.frame)
        self.verticalLayoutFrame.setObjectName("verticalLayoutFrame")
        self.labelActivityTitle = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setWeight(75)
        self.labelActivityTitle.setFont(font)
        self.labelActivityTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelActivityTitle.setObjectName("labelActivityTitle")
        self.verticalLayoutFrame.addWidget(self.labelActivityTitle)
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame)
        self.progressBar.setProperty("value", 50)
        self.progressBar.setObjectName("progressBar")
        self.progressLayout.addWidget(self.progressBar)
        self.labelProgress = QtWidgets.QLabel(parent=self.frame)
        self.labelProgress.setObjectName("labelProgress")
        self.progressLayout.addWidget(self.labelProgress)
        self.verticalLayoutFrame.addLayout(self.progressLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushButtonMoreInfo = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonMoreInfo.setObjectName("pushButtonMoreInfo")
        self.buttonLayout.addWidget(self.pushButtonMoreInfo)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.buttonLayout.addWidget(self.pushButtonAdd)
        self.verticalLayoutFrame.addLayout(self.buttonLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Activities View"))
        Dialog.setStyleSheet(_translate("Dialog", "\n"
"    QDialog {\n"
"        background-color: #f5f5f5;\n"
"    }\n"
"    QLabel {\n"
"        font-family: \'Arial\';\n"
"        color: #333333;\n"
"    }\n"
"    QPushButton {\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"        color: white;\n"
"        background-color: #4CAF50;\n"
"        border-radius: 10px;\n"
"        padding: 10px 20px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #45a049;\n"
"    }\n"
"    QFrame {\n"
"        background-color: #ffffff;\n"
"        border-radius: 20px;\n"
"        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\n"
"    }\n"
"   "))
        self.labelGreeting.setText(_translate("Dialog", "Hello, Name!"))
        self.labelProjectsNum.setText(_translate("Dialog", "Your projects: (number)"))
        self.frame.setStyleSheet(_translate("Dialog", "\n"
"       background-color: #ffffff;\n"
"       border-radius: 15px;\n"
"       box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);\n"
"      "))
        self.labelActivityTitle.setText(_translate("Dialog", "Activity Title"))
        self.progressBar.setStyleSheet(_translate("Dialog", "\n"
"            QProgressBar {\n"
"                background-color: #e0e0e0;\n"
"                border: none;\n"
"                border-radius: 10px;\n"
"            }\n"
"            QProgressBar::chunk {\n"
"                background-color: #4CAF50;\n"
"                border-radius: 10px;\n"
"            }\n"
"           "))
        self.labelProgress.setText(_translate("Dialog", "50%"))
        self.pushButtonMoreInfo.setText(_translate("Dialog", "More Info"))
        self.pushButtonAdd.setText(_translate("Dialog", "Add"))
